# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

#palette = "catppuccin_latte"
palette = "catppuccin_macchiato"
#  

format = """\
[](fg:blue)\
[   ](fg:surface0 bg:blue)\
$directory\
[](fg:surface0) \
[$git_branch$git_status$git_state$git_metrics](bg:tool_bg)\
$aws\
$golang\
$python\
$rust\
$terraform\
$character\
"""
right_format = """\
$status\
$cmd_duration\
$time\
"""

command_timeout = 1000

[palettes.dark]
os_host_fg = "#090C0C"
os_host_fg_root = "#ff0000"
os_host_bg = "#7DF9AA"
directory_host_fg = "#E4E4E4"
directory_host_bg = "#3B76F0"
tool_fg = "#3EC669"
tool_bg = "#29315A"
error_color = "#E84D44"
time_fg = "#8DFBD2"
time_bg = "#1C3A5E"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[aws]
symbol = '󰸏 '
format = '[](fg:pink)[$symbol](fg:surface0 bg:pink)[ $profile \($region\) \[$duration\] ](fg:text bg:surface0)[](fg:surface0) '

[aws.region_aliases]
eu-west-1 = "irl"
eu-west-2 = "uk"

[directory]
format = "[ $path ]($style)"
style = "fg:text bg:surface0"
read_only = " 󰌾"


[git_branch]
format = '[](fg:pink)[$symbol](fg:surface0 bg:pink)[ $branch(:$remote_branch)](fg:text bg:surface0)'
#format = '[](fg:tool_bg)[ $symbol$branch(:$remote_branch) ]($style)'
symbol = " "
style = "bg:tool_bg"
disabled = false

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
style = "fg:text bg:surface0"
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
disabled = false

[git_state]
disabled = true
style = "fg:text bg:surface0"

[git_metrics]
#format = '([+$added]($added_style))([-$deleted]($deleted_style))[](fg:tool_bg)'
format = '([+$added]($added_style))([-$deleted]($deleted_style))[](fg:surface0) '
added_style = "fg:green bg:surface0"
deleted_style = "fg:red bg:surface0"
disabled = false

[golang]
symbol = " "
format = "[](fg:pink)[$symbol](fg:surface0 bg:pink)[ $version](fg:text bg:surface0)[](fg:surface0) "

[cmd_duration]
format = "[](fg:blue)[  ](fg:surface0 bg:blue)[ $duration](fg:text bg:surface0)[](fg:surface0)"
style = "fg:bright-white bg:18"

[character]
format = '$symbol'
success_symbol = '[ ➜](fg:green) '
error_symbol = '[ ✗](fg:red) '
vimcmd_symbol = '[ ❮ ](bold green)'
vimcmd_replace_one_symbol = '[ ❮ ](bold purple)'
vimcmd_replace_symbol = '[ ❮ ](bold purple)'
vimcmd_visual_symbol = '[ ❮ ](bold yellow)'

[os]
disabled = false
style = "bg:os_host_bg fg:os_host_fg"

[rust]
format = "[](fg:pink)[$symbol](fg:surface0 bg:pink)[ $version](fg:text bg:surface0)[](fg:surface0) "
symbol = " "

[hostname]
disabled = false
ssh_only = true
ssh_symbol = '🌐'
style = "bg:os_host_bg fg:os_host_fg"
format = '[$hostname$ssh_symbol]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[](fg:blue)[󱑍 ](fg:surface0 bg:blue)[ $time](fg:text bg:surface0)[](fg:surface0)'

[python]
disabled = false
pyenv_version_name = true
style = "fg:blue bg:text"
format = '[](fg:pink)[${symbol}](bg:pink)[ ${pyenv_prefix}(${version} )(\($virtualenv\))](fg:text bg:surface0)[](fg:surface0)'

[status]
format = '[](fg:surface0)[$symbol $status ](fg:text bg:surface0)[](fg:surface0) '
disabled=false

[terraform]
disabled = false
style = "fg:text bg:surface0"
#symbol = "🛠️ "
symbol = ""
format = '[[](fg:pink)[${symbol} ](fg:surface0 bg:pink)${version}[](fg:tool_bg)]($style)'

[username]
style_user = "bg:os_host_bg fg:os_host_fg"
style_root = "bg:os_host_bg fg:os_host_fg_root"
format="[$user@]($style)"
